#!/bin/bash

if [[ -z $1 ]]; then
	echo "Please enter problem number:"
	read num
else
	num=$1
fi

if [[ -d ./$num ]]; then
	echo "Problem existed!"
	exit 1
fi

cp -r ./template ./$num

cd ./$num
printf "\n//====Comments====\\\\\n" > ./problem
touch ./input



